#!/bin/ksh
# Runs a command remotely on the Pi, assuming default credentials and device name.
# Copies a whole directory structure to the same location (relative to ~) on the Pi
#
# E.g.
#    cd ExamplePrograms; ../runbp python SimpleApp.py
#
# This script lives in the base directory of the content to be copied.
# DON'T PUT IT IN YOUR HOME DIRECTORY!!
# It deletes the corresponding directory on the Pi before copying the new structure over.
#
# To make it executable:
#      chmod a+x runpb
#
# To make ssh work without entering passwords, see
#      https://www.debian.org/devel/passwordlessssh
#
# Note - The windows will appear on the BrickPi's screen, not locally to this machine.

# Current working directory relative to home:
WorkingRelDir=${PWD#$HOME/}

# BrickPython project directory relative to home:
BrickPythonDir=$(cd $(dirname $0);echo $PWD)
BrickPythonRelativeDir=${BrickPythonDir#$HOME/}

(
    cd ~
    tar cf - $BrickPythonRelativeDir | ssh pi@raspberrypi "(rm -rf $BrickPythonRelativeDir; tar xf -)"
)
ssh -t pi@raspberrypi "(export DISPLAY=:1.0; cd $WorkingRelDir; $*)"
